spring.application.name=api-gateway
#server.port=8080
spring.profiles.active=local

spring.config.import=optional:configserver:http://localhost:8888
#
## ==============================
## EUREKA
## ==============================
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.instance.prefer-ip-address=true
#
## ==============================
## USER SERVICE
## ==============================
#spring.cloud.gateway.server.webflux.routes[0].id=user-service
#spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/admin/users/**
#
## ==============================
## OPERATOR SERVICE
## ==============================
#spring.cloud.gateway.server.webflux.routes[1].id=operator-service
#spring.cloud.gateway.server.webflux.routes[1].uri=lb://OPERATOR-SERVICE
#spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/operators/**,/api/admin/operators/**
#spring.cloud.gateway.server.webflux.routes[1].filters[0]=CircuitBreaker=name=operatorCircuitBreaker,fallbackUri=forward:/fallback/operator
#
## ==============================
## RECHARGE SERVICE
## ==============================
#spring.cloud.gateway.server.webflux.routes[2].id=recharge-service
#spring.cloud.gateway.server.webflux.routes[2].uri=lb://RECHARGE-SERVICE
#spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/recharges/**
#spring.cloud.gateway.server.webflux.routes[2].filters[0]=CircuitBreaker=name=rechargeCircuitBreaker,fallbackUri=forward:/fallback/recharge
#
## ==============================
## PAYMENT SERVICE
## ==============================
#spring.cloud.gateway.server.webflux.routes[3].id=payment-service
#spring.cloud.gateway.server.webflux.routes[3].uri=lb://PAYMENT-SERVICE
#spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/payments/**
#spring.cloud.gateway.server.webflux.routes[3].filters[0]=CircuitBreaker=name=paymentCircuitBreaker,fallbackUri=forward:/fallback/payment
#
## ==============================
## FALLBACK ROUTES
## ==============================
#spring.cloud.gateway.server.webflux.routes[4].id=recharge-fallback
#spring.cloud.gateway.server.webflux.routes[4].uri=forward:/fallback/recharge
#spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/fallback/recharge
#
#spring.cloud.gateway.server.webflux.routes[5].id=payment-fallback
#spring.cloud.gateway.server.webflux.routes[5].uri=forward:/fallback/payment
#spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/fallback/payment
#
#spring.cloud.gateway.server.webflux.routes[6].id=operator-fallback
#spring.cloud.gateway.server.webflux.routes[6].uri=forward:/fallback/operator
#spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/fallback/operator
#
## ==============================
## JWT
## ==============================
#jwt.secret=${JWT_SECRET}
#
## ==============================
## ACTUATOR
## ==============================
#management.endpoints.web.exposure.include=*
#
## ==============================
## SWAGGER AGGREGATION
## ==============================
#springdoc.swagger-ui.urls[0].name=User Service
#springdoc.swagger-ui.urls[0].url=/v3/api-docs/user
#
#springdoc.swagger-ui.urls[1].name=Operator Service
#springdoc.swagger-ui.urls[1].url=/v3/api-docs/operator
#
#springdoc.swagger-ui.urls[2].name=Recharge Service
#springdoc.swagger-ui.urls[2].url=/v3/api-docs/recharge
#
#springdoc.swagger-ui.urls[3].name=Payment Service
#springdoc.swagger-ui.urls[3].url=/v3/api-docs/payment
#
## ==============================
## SWAGGER ROUTES
## ==============================
#spring.cloud.gateway.server.webflux.routes[7].id=user-swagger
#spring.cloud.gateway.server.webflux.routes[7].uri=lb://USER-SERVICE
#spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/v3/api-docs/user
#spring.cloud.gateway.server.webflux.routes[7].filters[0]=RewritePath=/v3/api-docs/user,/v3/api-docs
#
#spring.cloud.gateway.server.webflux.routes[8].id=operator-swagger
#spring.cloud.gateway.server.webflux.routes[8].uri=lb://OPERATOR-SERVICE
#spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/v3/api-docs/operator
#spring.cloud.gateway.server.webflux.routes[8].filters[0]=RewritePath=/v3/api-docs/operator,/v3/api-docs
#
#spring.cloud.gateway.server.webflux.routes[9].id=recharge-swagger
#spring.cloud.gateway.server.webflux.routes[9].uri=lb://RECHARGE-SERVICE
#spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/v3/api-docs/recharge
#spring.cloud.gateway.server.webflux.routes[9].filters[0]=RewritePath=/v3/api-docs/recharge,/v3/api-docs
#
#spring.cloud.gateway.server.webflux.routes[10].id=payment-swagger
#spring.cloud.gateway.server.webflux.routes[10].uri=lb://PAYMENT-SERVICE
#spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/v3/api-docs/payment
#spring.cloud.gateway.server.webflux.routes[10].filters[0]=RewritePath=/v3/api-docs/payment,/v3/api-docs
#resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
## How long to wait before trying the service again (in milliseconds)
#resilience4j.circuitbreaker.instances.operatorCircuitBreaker.wait-duration-in-open-state=5000
#resilience4j.circuitbreaker.instances.paymentCircuitBreaker.wait-duration-in-open-state=5000
## Time limit for a request before it's considered a failure
#resilience4j.timelimiter.configs.default.timeout-duration=3s