spring.application.name=payment-service
spring.profiles.active=local

spring.config.import=optional:configserver:http://localhost:8888

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
