spring.application.name=notification-service
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=local

# Gmail SMTP — credentials from environment variables
spring.mail.username=${MAIL_USERNAME:recharge.omni@gmail.com}
spring.mail.password=${MAIL_PASSWORD:kvsw lxac qkpz ppmu}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
